dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config
      - g++
      - g++-4.9
      - g++-5
      - pkg-config
      - zip
      - zlib1g-dev
      - unzip


before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel-0.4.4-installer-linux-x86_64.sh
  - wget https://github.com/bazelbuild/bazel/releases/download/0.4.4/bazel-0.4.4-installer-linux-x86_64.sh.sha256
  - sha256sum -c bazel-0.4.4-installer-linux-x86_64.sh.sha256
  - chmod +x bazel-0.4.4-installer-linux-x86_64.sh
  - ./bazel-0.4.4-installer-linux-x86_64.sh --user
  - export PATH="$PATH:$HOME/bin"


script:
  - bazel run verify
  - python lint.py


notifications:
  email: false

